USE w3schools;

DESC MyTable13;

-- MODIFY COLUMN : COLUMN 타입 변경
ALTER TABLE MyTable13
MODIFY COLUMN Col20 VARCHAR(40);

SELECT * FROM MyTable13;

ALTER TABLE MyTable13
MODIFY COLUMN Col13 VARCHAR(40);

-- 7개의 문자열을 가지고 있는 Col13을 3개의 문자열까지만 허락하도록 수정 불가능
ALTER TABLE MyTable13
MODIFY COLUMN Col13 VARCHAR(3); -- DANGER

DESC MyTable13;
ALTER TABLE MyTable13
MODIFY COLUMN Col7 INT;

-- 
ALTER TABLE MyTable13
MODIFY COLUMN Col8 VARCHAR(9) FIRST;

DESC MyTable13;

ALTER TABLE MyTable13
MODIFY COLUMN Col8 VARCHAR(8) AFTER Col20;

-- MyTable13의 아무 컬럼의 위치 변경
ALTER TABLE MyTable13
MODIFY COLUMN Col5 DATE FIRST;